# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29a708d07fab4f6de2347cd0dd3edf1c91d2967aad1a64c80829bd6d185814f6838a75498979902abaed311b56ceeaaa4b3f02b0c0282c4c119041d141274d5e

test:
  secret_key_base: 45f5b035c86d53dda08efc0925a12a79b3d8b2f35cef98a903a43ed1d832cc5f7af70ecdabdc3c78ef7994b45bdd947984ab43c58a412777ad04f57d5025d009

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
